config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants, except: [:update, :edit, :destroy] do
    resources :reviews, except: [:index, :update, :edit, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  TYPE = %w(chinese italian japanese french belgian)
  validates :name, uniqueness: true, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :category, presence: true, inclusion: { in: TYPE }
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  RATINGS = [0, 1, 2, 3, 4, 5]
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, inclusion: { in: RATINGS }, numericality: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
    redirect_to restaurants_path(@restaurant)
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if  @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def show
    @review = Review.find(params[:id])
  end

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name, label: 'Enter a name please', error: 'Name is mandatory, please specify' %>
  <%= f.input :address, label: 'Enter an address please', error: 'Address is mandatory, please specify' %>
  <%= f.input :phone_number, label: 'Enter a phone number please', error: 'Phone number is mandatory, please specify' %>
  <%= f.input :category, label: 'Enter a category please', error: 'Category is mandatory, please specify', collection: Restaurant::TYPE %>
  <%= f.submit "add a restaurant", class: "btn btn-primary" %>

<% end %>

app/views/restaurants/index.html.erb
<h1>List of restaurants</h1>
<% @restaurants.each do |restaurant| %>
  <h2><%= restaurant.name %></h2>
  <%= link_to "Show details", restaurant_path(restaurant), class: "btn btn-primary"%>

<% end %>

  <%= link_to "Add new restaurant", new_restaurant_path, class: "btn btn-primary"%>

app/views/restaurants/new.html.erb
<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/show.html.erb
<h2><%= @restaurant.name %></h2>
<p><%= @restaurant.address %></p>
<p><%= @restaurant.phone_number %></p>
<p><%= @restaurant.category %></p>
<%= link_to "Add review", new_restaurant_review_path(@restaurant), class: "btn btn-primary" %>

app/views/reviews/_form.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating, label: 'Enter a rating please', error: 'Rating is mandatory, please specify', collection: Review::RATINGS %>
  <%= f.submit "add a review", class: "btn btn-primary" %>

<% end %>

app/views/reviews/new.html.erb
<%= render 'form', review: @review %>

app/views/reviews/show.html.erb
<%= @review.restaurant.name %>
<%= @review.content %>
<%= link_to "Go back to list", restaurants_path, class: "btn btn-primary"%>